#!/usr/bin/env bash
# When any of the global *-commands acl properties are set, allow normal users
# to run only these commands.

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "${BASH_SOURCE[0]}")/internal-functions"

fn-acl-load-global-properties
USER_COMMANDS="$(fn-acl-global-property user-commands)"
PER_APP_COMMANDS="$(fn-acl-global-property per-app-commands)"
PER_SERVICE_COMMANDS="$(fn-acl-global-property per-service-commands)"
LINK_COMMANDS="$(fn-acl-global-property link-commands)"

SSH_USER=$1
SSH_NAME=$2
shift 2

[[ -z "$USER_COMMANDS" && -z "$PER_APP_COMMANDS" && -z "$PER_SERVICE_COMMANDS" && -z "$LINK_COMMANDS" ]] && exit 0
[[ "$SSH_USER" == "root" ]] && exit 0
fn-acl-is-command-line && fn-acl-allow-command-line && exit 0
fn-acl-is-super-user "$SSH_NAME" && exit 0

CMD=$1

for allowed in $USER_COMMANDS; do
  [[ "$CMD" == "$allowed" ]] && exit 0
done

for allowed in $PER_APP_COMMANDS; do
  if [[ "$CMD" == "$allowed" ]]; then
    if [[ -z "$2" ]]; then
      dokku_log_fail "An app name is required"
    fi
    # shellcheck disable=SC1003
    APP_NAME="$(echo "$2" | perl -pe 's/(?<!\\)'\''//g' | sed 's/\\'\''/'\''/g' | sed 's/^\///g')"
    fn-check-app-acl "$APP_NAME" "$SSH_NAME" && exit 0
  fi
done

for allowed in $PER_SERVICE_COMMANDS; do
  if [[ "$CMD" == "$allowed" ]]; then
    if [[ -z "$2" ]]; then
      dokku_log_fail "A service name is required"
    fi

    fn-check-service-acl "$CMD" "$2" "$SSH_NAME" && exit 0
  fi
done

for allowed in $LINK_COMMANDS; do
  if [[ "$CMD" == "$allowed" ]]; then
    if [[ -z "$2" ]]; then
      dokku_log_fail "A service name is required"
    fi

    if [[ -z "$3" ]]; then
      dokku_log_fail "An app name is required"
    fi

    (fn-check-service-acl "$CMD" "$2" "$SSH_NAME") && (fn-check-app-acl "$3" "$SSH_NAME") && exit 0

    # An appropriate failure message has already been sent by the check- function
    exit 1
  fi
done

dokku_log_fail "User $SSH_NAME does not have permissions to run $CMD"
