#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/internal-functions"

cmd-acl-allowed-services() {
  #E show services of a given type that the user has access to
  #E dokku $PLUGIN_COMMAND_PREFIX:list redis birds
  #A type, type of service
  #A username, user to check for access
  declare desc="list services of type <type> that the user has access to"
  local cmd="$PLUGIN_COMMAND_PREFIX:allowed-services" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE_TYPE="$1" USERNAME="$2"

  if [[ -n "${NAME:-}" ]]; then
    dokku_log_fail "This command can only be run using the local dokku command on the target host"
  fi

  if [[ -z "$SERVICE_TYPE" ]]; then
    dokku_log_fail "No service type specified"
  fi

  if [[ -z "$USERNAME" ]]; then
    dokku_log_fail "No username specified"
  fi

  local PLUGIN_DATA_ROOT="$DOKKU_LIB_ROOT/services/$SERVICE_TYPE"
  if [[ ! -d "$PLUGIN_DATA_ROOT" ]]; then
    dokku_log_fail "$SERVICE_TYPE service plugin not detected"
  fi

  if fn-acl-is-super-user "$USERNAME"; then
    find "$PLUGIN_DATA_ROOT" -follow -maxdepth 1 -mindepth 1 -type d ! -name '.*' -printf "%f\n" 2>/dev/null | sort || true
    return
  fi

  pushd "$PLUGIN_DATA_ROOT" >/dev/null
  ls -d */acl/$USERNAME 2>/dev/null | cut -d '/' -f1 || true
  popd >/dev/null
}

cmd-acl-allowed-services "$@"
