#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/acl/functions"

acl_main_cmd() {
  declare desc="display acl plugin help content"
  local cmd="acl"
  help_formatted
}

acl_main_cmd "$@"
