#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/internal-functions"

cmd-acl-list() {
  #E show users that have access to the lolipop app
  #E dokku $PLUGIN_COMMAND_PREFIX:list lolipop
  #A app, app to run command against
  declare desc="show list of users with access to <app>"
  local cmd="$PLUGIN_COMMAND_PREFIX:list" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"

  if [[ -z "$APP" ]]; then
    local INSTALLED_APPS=$(dokku_apps)
    for APP in $INSTALLED_APPS; do
      fn-acl-check-app "$APP"
      dokku_log_info2_quiet "${APP} acl list"
      ls -1 "$DOKKU_ROOT/$APP/acl" >&2 2>/dev/null || true
    done
  else
    fn-acl-check-app "$APP"
    ls -1 "$DOKKU_ROOT/$APP/acl" >&2 2>/dev/null || true
  fi
}

cmd-acl-list "$@"
