#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/internal-functions"

cmd-acl-remove() {
  declare desc="revoke <user>'s access to <app>"
  declare cmd="acl:remove"
  [[ "$1" == "$cmd" ]] && shift 1
  declare APP="$1" USER="$2"
  local ACL_PATH="$DOKKU_ROOT/$APP/acl"
  local ACL_FILE="$ACL_PATH/$USER"

  fn-acl-check-app "$APP"

  if [[ -z "$USER" ]]; then
    dokku_log_fail "Please specify a user name"
  fi

  [[ -f "$ACL_FILE" ]] && rm "$ACL_FILE";
  [[ -d "$ACL_PATH" ]] && [[ -z "$(ls "$ACL_PATH")" ]] && rmdir "$ACL_PATH";
}

cmd-acl-remove "$@"
