#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/internal-functions"

cmd-acl-remove-service() {
  #E revoke the servuser user's access to the birds Redis service
  #E dokku $PLUGIN_COMMAND_PREFIX:remove-service redis birds servuser
  #A type, type of service
  #A service, service to run command against
  #A user, a user to revoke access
  declare desc="revoke <user>'s access to <service> of type <type>"
  local cmd="$PLUGIN_COMMAND_PREFIX:remove-service" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE_TYPE="$1" SERVICE="$2" USER="$3"

  fn-acl-check-service "$SERVICE_TYPE" "$SERVICE"

  local ACL_PATH="$DOKKU_LIB_ROOT/services/$SERVICE_TYPE/$SERVICE/acl"
  local ACL_FILE="$ACL_PATH/$USER"

  if [[ -z "$USER" ]]; then
    dokku_log_fail "Please specify a user name"
  fi

  [[ -f "$ACL_FILE" ]] && rm "$ACL_FILE";
  if [[ -d "$ACL_PATH" ]] && [[ -z "$(ls "$ACL_PATH")" ]]; then
    rmdir "$ACL_PATH"
  else
    exit 0
  fi
}

cmd-acl-remove-service "$@"
