#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/internal-functions"

cmd-acl-report() {
  #E displays a acl report for all apps
  #E dokku $PLUGIN_COMMAND_PREFIX:report
  #E displays a acl report for one app
  #E dokku $PLUGIN_COMMAND_PREFIX:report lolipop
  #A app, app to run command against
  declare desc="displays a acl report for one or more apps"
  local cmd="$PLUGIN_COMMAND_PREFIX:report" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"

  cmd-acl-report-all "$@"
}

cmd-acl-report "$@"
